apiVersion: config.istio.io/v1alpha2
kind:       RouteRule
metadata:
  name: dic-cookie-v2
spec:
  precedence: 3
  destination:
    name: dictionary
  match:
    source:
      name: hangman
    request:
      headers:
        cookie:
          regex: "^(.*?;)?(dic=trump)(;.*)?$"
  route:
    - labels:
        version: v2
      weight: 100
