apiVersion: config.istio.io/v1alpha2
kind:       RouteRule
metadata:
  name: dic-fault
spec:
  precedence: 1
  destination:
    name: dictionary
  match:
    source:
      name: hangman
  httpFault:
    abort:
      percent:    50
      httpStatus: 400
