---
apiVersion: config.istio.io/v1alpha2
kind:       RouteRule
metadata:
  name: dic-timeout
spec:
  precedence: 2
  destination:
    name: dictionary
  route:
  - labels:
      version: v1
  httpReqTimeout:
    simpleTimeout:
      timeout: 10s