apiVersion: config.istio.io/v1alpha2
kind:       RouteRule
metadata:
  name: dic-delay
spec:
  precedence: 2
  destination:
    name: dictionary
  match:
    source:
      name: hangman
  httpFault:
    delay:
      percent: 100
      fixedDelay: 2s
---
apiVersion: config.istio.io/v1alpha2
kind:       RouteRule
metadata:
  name: dic-timeout
spec:
  precedence: 2
  destination:
    name: dictionary
  match:
    source:
      name: hangman
  route:
  - labels:
      version: v1
    weight: 100
  httpReqTimeout:
    simpleTimeout:
      timeout: 1s