kind:       Deployment
apiVersion: extensions/v1beta1
metadata:
  name: dictionary-v2
  labels:
    group: hangman
    app:   dictionary
spec:
  replicas: 1
  template:
    metadata:
      labels:
        group:   hangman
        app:     dictionary
        version: v2
    spec:
      imagePullSecrets:
      - name: quay-secret
      containers:
      - name:            dictionary
        image:           quay.io/derailed/dictionary:1.1
        imagePullPolicy: IfNotPresent
        args:            ["--dic", "trump"]
        resources:
          limits:
            cpu:    1.0m
            memory: 5Mi
        ports:
        - name:          api
          containerPort: 9090
