---
# Dictionary all
apiVersion: config.istio.io/v1alpha2
kind:       RouteRule
metadata:
  name: dic-all-v1
spec:
  precedence: 1
  destination:
    name: dictionary
  route:
  - labels:
      version: v1
    weight: 100