apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: dictionary-fault
spec:
  destination:
    name: dictionary
  route:
  - labels:
      version: v1
  httpFault:
    delay:
      percent:    10
      fixedDelay: 5s
