apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: dic-80
spec:
  precedence: 1
  ## Used by services inside the Kubernetes cluster
  destination:
    name: dictionary
  route:
  - labels:
      version: v1
    weight: 20
  - labels:
      version: v2
    weight: 80