apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: dic-fault
spec:
  precedence: 1
  destination:
    name: dictionary
  route:
  - labels:
      version: v1
  httpFault:
    delay:
      percent:    100
      fixedDelay: 5s
