---
# Dictionary all
apiVersion: config.istio.io/v1alpha2
kind:       RouteRule
metadata:
  name: dic-v2-fault
spec:
  precedence: 1
  destination:
    name: dictionary
  route:
  - labels:
      version: v2
    weight: 100
  httpFault:
    abort:
      percent:    50
      httpStatus: 400