apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: dic-v2-timeout
spec:
  destination:
    name: dictionary
  route:
  - labels:
      version: v2
  httpReqTimeout:
    simpleTimeout:
      timeout: 10s
