---
# Dictionary all
apiVersion: config.istio.io/v1alpha2
kind:       RouteRule
metadata:
  name: dic-trump
spec:
  precedence: 1
  destination:
    name: dictionary
  route:
  - labels:
      version: v1
    weight: 0
  - labels:
      version: v2
    weight: 100