kind:       Deployment
apiVersion: extensions/v1beta1
metadata:
  name: dictionary-v1
  labels:
    group: hangman
    app:   dictionary
spec:
  replicas: 1
  template:
    metadata:
      labels:
        group:   hangman
        app:     dictionary
        version: v1
    spec:
      imagePullSecrets:
      - name: quay-secret
      containers:
      - name:            dictionary
        image:           quay.io/derailed/dictionary:1.1
        imagePullPolicy: IfNotPresent
        args:            ["--dic", "standard"]
        # livenessProbe:
        #   httpGet:
        #     path: /dictionary/v1/health
        #     port: 9094
        #   initialDelaySeconds: 15
        #   timeoutSeconds:      15
        resources:
          limits:
            cpu:    0.5m
            memory: 4Mi
        ports:
        - name:          http
          containerPort: 9094
