kind:       Deployment
apiVersion: extensions/v1beta1
metadata:
  name: dictionary
  labels:
    group: hangman
    app:   dictionary
spec:
  replicas: 1
  template:
    metadata:
      labels:
        group: hangman
        app:   dictionary
    spec:
      imagePullSecrets:
      - name: quay-secret
      containers:
      - name:  dictionary
        image: quay.io/derailed/dictionary:1.1
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu:    0.5m
            memory: 4Mi
        ports:
        - name:          api
          containerPort: 9090
