kind:       Service
apiVersion: v1
metadata:
  name: dictionary
  labels:
    group: hangman
    app:   dictionary
spec:
  type: NodePort
  selector:
    app: dictionary
  ports:
    - name:       api
      port:       9090
      nodePort:   30400
      targetPort: api
