kind:       Service
apiVersion: v1
metadata:
  name: hangman
  labels:
    app: hangman
spec:
  selector:
    app: hangman
  ports:
    - name:       http
      protocol:   TCP
      port:       9096
      targetPort: 9096
