kind:       Deployment
apiVersion: extensions/v1beta1
metadata:
  name: game-v1
  labels:
    app: game
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app:     game
        version: v1
    spec:
      imagePullSecrets:
      - name: quay-secret
      containers:
      - name:            game
        image:           quay.io/derailed/game:1.2
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu:    1.0m
            memory: 5Mi
        ports:
        - name:          http
          containerPort: 9095
