kind:       Service
apiVersion: v1
metadata:
  name: game
  labels:
    app: game
spec:
  selector:
    app: game
  ports:
    - name:       http
      protocol:   TCP
      port:       9095
      targetPort: 9095
